### ISSUE TITLE
Pulling image via `docker pull ghcr.io/rmi-pacta/workflow.pacta:main` not working on `ARM64` architecture

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/workflow.pacta#29] opened 2024-01-09 16:37 UTC
I've been trying to test this repo out, and I am unable to pull the image from `ghcr.io` on `ARM64` architecture. Is that expected behavior?

<img width="699" alt="Screenshot 2024-01-09 at 10 36 33" src="https://github.com/RMI-PACTA/workflow.pacta/assets/8741309/9b470d41-c75a-47db-87da-791d4e632310">

@AlexAxthelm maybe has info here? Maybe we need to specify the platform in the build actions here: https://github.com/RMI-PACTA/workflow.pacta/tree/main/.github/workflows

**Comment by jdhoffa** [comment] 2024-01-09 16:39
Likely related to #14 and #20

**Comment by cjyetman** [comment] 2024-01-09 16:56
Also of note... the current build process *does* create two images, but it's unclear what architecture the second is for, e.g. https://github.com/RMI-PACTA/workflow.pacta/pkgs/container/workflow.pacta/159147745?tag=main (then click the "OS / Arch" tab)

**Comment by cjyetman** [comment] 2024-01-10 12:56
I think the problem is/was that now that we're using `buildx` it builds image/s and a manifest, so you'll need to specify `platform=amd64` if you're on arm64 and it's defaulting to `platform=arm64`.

**Comment by AlexAxthelm** [comment] 2024-02-19 14:52
I believe that this is blocked by #32

**Comment by AlexAxthelm** [comment] 2024-05-09 12:11
Closing this as ARM64 build have been available for a while, and we're using the standard RMI build process as of closing #50

**Closed as completed by AlexAxthelm** 2024-05-09 12:11 UTC
